@startuml
'https://plantuml.com/sequence-diagram

title Change Plan Details N1

autoactivate on
autonumber

actor "MarketingDirector" as MarketingDirector
participant ":PlanC" as PlanC


activate MarketingDirector

MarketingDirector -> PlanC: PATCH /api/plan/{planName}
PlanC --> MarketingDirector: 200 OK
@enduml
