@startuml
'https://plantuml.com/sequence-diagram


actor "Subscriber" as Subscriber
participant ":SubscriptionsC" as SubscriptionsC

participant ":MessageBroker" as MB

Subscriber -> SubscriptionsC: PATCH: api/subscription/plan/{planName}


SubscriptionsC --> SubscriptionsC: update(subscription)
SubscriptionsC -> MB: publish{"sub.updated.*, subscription"}

SubscriptionsC --> Subscriber: 200 OK
...
MB --> SubscriptionsC:notify{subscription}

@enduml
